# 网站标题
title: promise

# 网站描述
description: 记录笔记喵

# 作者信息
author:
  name: promise
  email: 你的邮箱
  url: https://github.com/你的GitHub用户名

# 仓库信息
repository: 你的GitHub用户名/learning_blog

# 显示下载按钮
show_downloads: false

# Google Analytics（可选）
google_analytics:

# 使用的主题
theme: jekyll-theme-cayman

# 插件
gems:
  - jekyll-seo-tag
  - jekyll-sitemap

# permalink格式
permalink: /:year/:month/:day/:title/

# 分页
paginate: 5
paginate_path: "/page/:num/"